version: '3'

services:
  db:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=aircraft_db
    ports:
      - "5432:5432"
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  api:
    build: .
    env_file:
      - .env
    environment:
      DB_HOST: db
    ports:
      - "8001:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy
    command: ["/app/start.sh"]

volumes:
  postgres_data:
